version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    container_name: zoo1 
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 server.4=zoo4:2891:3891 server.5=zoo5:2892:3892
  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    container_name: zoo2     
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2889:3889 server.3=zoo3:2890:3890 server.4=zoo4:2891:3891 server.5=zoo5:2892:3892
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    container_name: zoo3    
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=0.0.0.0:2890:3890 server.4=zoo4:2891:3891 server.5=zoo5:2892:3892
  zoo4:
    image: zookeeper
    restart: always
    hostname: zoo4
    container_name: zoo4     
    ports:
      - 2184:2181
      - 2891:2888
      - 3891:3888
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 server.4=0.0.0.0:2891:3891 server.5=zoo5:2892:3892
  zoo5:
    image: zookeeper
    restart: always
    hostname: zoo5
    container_name: zoo5     
    ports:
      - 2185:2181
      - 2892:2888
      - 3892:3888
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2889:3889 server.3=zoo3:2890:3890 server.4=zoo4:2891:3891 server.5=0.0.0.0:2892:3892
